project:
  type: book
  output-dir: docs
  
  

book:
  title: "purrr FR"
  page-footer: "Merci à [Git](https://git-scm.com/), [github](https://github.com/), [Python](https://www.python.org/), [quarto](https://quarto.org/), [RStudio](https://posit.co/download/rstudio-desktop/), [R](https://cran.rstudio.com/) et [Wikipédia](https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal)"
  
  author:
    - name: Roger MARTIN
      email: Roger57que@free.fr
    - name: Jenny BRYAN
      url: https://jennybc.github.io/purrr-tutorial/bk00_vectors-and-lists.html
  date: "03/06/2024"
  date-format: "ddd D MMM YYYY"
  chapters:
    - index.qmd
    - part: "Notions de base"
      chapters: 
        - 101-vecteurs-et-listes.qmd
    - intro.qmd
    - summary.qmd
    
  appendices: 
    - references.qmd
    
  sidebar: 
    tools: 
      - icon: github
        menu: 
          - text: Code source
            url: https://github.com/CzernaiFR/Loto
          - text: Site
            url: https://czernaifr.github.io/Loto/
  
bibliography: references.bib
lang: fr-FR
license: CC BY-NC-SA
number-depth: 3
execute: 
  echo: fenced

format:
  html:
    theme: superhero
    fontsize: 1.2em
    highlight-style: vim-dark
    reference-location: margin
    citations-hover: true
    citation-location: margin
    citation: true
    citeproc: true
    grid: 
      sidebar-width: 200px
      body-width: 780px
      margin-width: 320px
      gutter-width: 1rem
    
  pdf:
    documentclass: scrreprt



